name: Model Submission
description: Submit a new model entry
title: "[Model]: "
labels: ["model-entry"]
body:
  - type: markdown
    attributes:
      value: |
        please fill out the details for the new model below.

  # creator: creatorEnum
  - type: dropdown
    id: creator
    attributes:
      label: creator
      options:
        - Google
        - Black Forest Labs
        - fal
    validations:
      required: true

  # name: z.string()
  - type: input
    id: name
    attributes:
      label: name
      description: full model name
      placeholder: e.g. Gemini 2.5 Flash Image
    validations:
      required: true

  # nickname: z.string().optional()
  - type: input
    id: nickname
    attributes:
      label: nickname
      description: the unofficial name the model is known for
      placeholder: e.g. Nano Banana
    validations:
      required: false

  # family: z.string()
  - type: input
    id: family
    attributes:
      label: family
      placeholder: e.g. Gemini
    validations:
      required: true

  # version: z.string().optional()
  - type: input
    id: version
    attributes:
      label: version
      placeholder: e.g. 2.5
    validations:
      required: false

  # variant: z.array(z.string()).optional()
  - type: textarea
    id: variant
    attributes:
      label: variants
      description: one per line
      placeholder: e.g. Flash
        | Image
    validations:
      required: false

  # aka: z.array(z.string()).optional()
  - type: input
    id: aka
    attributes:
      label: aka
      description: list of additional names the model is known for, one per line
    validations:
      required: false

  # "release date": z.coerce.date()
  - type: input
    id: release_date
    attributes:
      label: release date
      description: official date of release in YYYY-MM-DD format
      placeholder: YYYY-MM-DD
    validations:
      required: true

  # "is preview release": z.stringbool().or(z.boolean())
  - type: checkboxes
    id: is_preview_release
    attributes:
      label: is preview release?
      description: is this a beta or preview version?
      options:
        - label: aaa
    validations:
      required: true

  # "base model": modelIdString.optional()
  - type: input
    id: base_model
    attributes:
      label: base model id
      description: the id of the base model if applicable
      placeholder: e.g. black-forest-labs/flux-2-dev
    validations:
      required: false
