name: Model Submission
description: Submit a new model entry
title: "[Model]: "
labels: ["model-entry"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details for the new model below.

  # creator: creatorEnum
  - type: dropdown
    id: creator
    attributes:
      label: Creator
      description: Select the organization that created the model.
      options:
        - Google
        - Black Forest Labs
        - fal
    validations:
      required: true

  # name: z.string()
  - type: input
    id: name
    attributes:
      label: Name
      description: The official name of the model.
      placeholder: e.g. Flux Pro
    validations:
      required: true

  # nickname: z.string().optional()
  - type: input
    id: nickname
    attributes:
      label: Nickname
      description: (Optional) A common nickname or alias.
    validations:
      required: false

  # family: z.string()
  - type: input
    id: family
    attributes:
      label: Family
      description: The model family this belongs to.
      placeholder: e.g. Flux, Gemini, etc.
    validations:
      required: true

  # version: z.string().optional()
  - type: input
    id: version
    attributes:
      label: Version
      description: (Optional) The specific version string.
      placeholder: e.g. v1.0, 1.5
    validations:
      required: false

  # variant: z.array(z.string()).optional()
  - type: textarea
    id: variant
    attributes:
      label: Variants
      description: (Optional) Comma-separated list of variants.
      placeholder: e.g. fp16, quantized, diffusers
    validations:
      required: false

  # aka: z.array(z.string()).optional()
  - type: input
    id: aka
    attributes:
      label: AKA (Also Known As)
      description: (Optional) Comma-separated list of other names.
    validations:
      required: false

  # "release date": z.coerce.date()
  - type: input
    id: release_date
    attributes:
      label: Release Date
      description: Date of release in YYYY-MM-DD format.
      placeholder: YYYY-MM-DD
    validations:
      required: true

  # "is preview release": z.stringbool().or(z.boolean())
  - type: dropdown
    id: is_preview_release
    attributes:
      label: Is Preview Release?
      description: Is this a beta or preview version?
      options:
        - "false"
        - "true"
      default: 0
    validations:
      required: true

  # "base model": modelIdString.optional()
  - type: input
    id: base_model
    attributes:
      label: Base Model ID
      description: (Optional) The ID of the base model if applicable.
    validations:
      required: false
